name = "mbs-tools"
compatibility_date = "2025-06-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mbspharmacy"
database_id = "11e3ce98-a697-48a2-961f-eab01a07c2db"
